base/models.py
# -*- coding: utf-8 -*-

"""
    base.models
    ~~~~~~~~~~~

    The most common models for the whole project.

    :copyright: (c) 2012 by Roman Semirook.
    :license: BSD, see LICENSE for more details.
"""

from flask.ext.login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from ext import db


class CRUDMixin(object):
    __table_args__ = {'extend_existing': True}

    id = db.Column(db.Integer, primary_key=True)

    @classmethod
    def get_by_id(cls, id):
        if any(
            (isinstance(id, basestring) and id.isdigit(),
             isinstance(id, (int, float))),
        ):
            return cls.query.get(int(id))
        return None

    @classmethod
    def create(cls, **kwargs):
        instance = cls(**kwargs)
        return instance.save()

    def update(self, commit=True, **kwargs):
        for attr, value in kwargs.iteritems():
            setattr(self, attr, value)
        return commit and self.save() or self

    def save(self, commit=True):
        db.session.add(self)
        if commit:
            db.session.commit()
        return self

    def delete(self, commit=True):
        db.session.delete(self)
        return commit and db.session.commit()


class User(UserMixin, CRUDMixin, db.Model):
    __tablename__ = 'users'

    username = db.Column(db.String(32))
    email = db.Column(db.String(32), unique=True)
    password = db.Column(db.String(32))

    def __init__(self, username, email, password):
        self.username = username
        self.email = email
        self.password = generate_password_hash(password)

    def __repr__(self):
        return u'<User %r>' % self.username

    def check_password(self, password):
        return check_password_hash(self.password, password)

    @classmethod
    def get_by_email(cls, email):
        return cls.query.filter_by(email=email).first()

base/forms.py
# -*- coding: utf-8 -*-

"""
    base.forms
    ~~~~~~~~~~

    The most common forms for the whole project.

    :copyright: (c) 2012 by Roman Semirook.
    :license: BSD, see LICENSE for more details.
"""

from flask.ext.wtf import Form
from wtforms import TextField, PasswordField
from wtforms.validators import Email, Required


class LoginForm(Form):
    email = TextField('Login', validators=[Required(), Email()])
    password = PasswordField('Password', validators=[Required()])

app.py
# -*- coding: utf-8 -*-

"""
    application
    ~~~~~~~~~~~

    Application initialization
    and app-specific registrations.

    :copyright: (c) 2012 by Roman Semirook.
    :license: BSD, see LICENSE for more details.
"""

from flask.ext.assets import Bundle
from helpers import AppFactory
from settings import DevelopmentConfig
from ext import assets


app = AppFactory(DevelopmentConfig).get_app(__name__)


# Assets zone

css_base_bundle = ['css/reset.css', 'css/typo.css', 'css/style.css',
                   'css/page.css', 'css/forms.css']

css_base = Bundle(*css_base_bundle, filters='cssmin', output='gen/base.css')
assets.register('css_base', css_base)

js_base_bundle = ['js/libs/json2.js', 'js/libs/jquery-1.8.2-min.js',
                  'js/libs/underscore-1.4.2-min.js', 'js/libs/backbone-0.9.2-min.js']

js_base = Bundle(*js_base_bundle, filters='jsmin', output='gen/base.js')
assets.register('js_base', js_base)

if __name__ == '__main__':
	app.run()

base/__init__.py
# -*- coding: utf-8 -*-
from flask import Blueprint


base = Blueprint('base', __name__,
                 template_folder='templates',
                 url_prefix='/')

from views import *

base/views.py
# -*- coding: utf-8 -*-

"""
    base.views
    ~~~~~~~~~~

    The most common views for the whole project.

    :copyright: (c) 2012 by Roman Semirook.
    :license: BSD, see LICENSE for more details.
"""

from flask.templating import render_template
from flask.views import MethodView
from flask import flash, redirect, request, url_for
from flask.ext.login import login_user, login_required, logout_user
from ext import login_manager
from base import base
from base.forms import LoginForm
from base.models import User


class FrontView(MethodView):

    def get(self):
        return render_template('base/main.html')

base.add_url_rule('', view_func=FrontView.as_view('front_page'))


class LoginView(MethodView):
    _messages = {'success': 'You are the boss!',
                 'invalid_auth': 'Who are you?',
                 'invalid_form': 'Invalid form.',
                 }

    def get(self):
        return render_template('login.html', form=LoginForm())

    def post(self):
        form = LoginForm()
        if not form.validate_on_submit():
            flash(self._messages['invalid_form'])
            return render_template('login.html', form=form)

        user = User.get_by_email(form.email.data)
        if user and user.check_password(form.password.data):
            login_user(user)
            flash(self._messages['success'])
        else:
            flash(self._messages['invalid_auth'])
            return redirect(url_for('base.login'))

        return redirect(request.args.get('next') or url_for('base.front_page'))

def hello():
    return 'asdfa'
base.add_url_rule('hello', view_func=hello, methods=['GET'])

base.add_url_rule('login1', view_func=LoginView.as_view('login'))

@login_manager.user_loader
def load_user(user_id):
    return User.get_by_id(user_id)


login_manager.login_view = 'base.login'
login_manager.login_message = 'You have to log in to access this page.'



@login_required
def logout():
    logout_user()
    return redirect(url_for('base.front_page'))

base.add_url_rule('logout', view_func=logout, methods=['POST'])

info/__init__.py
# -*- coding: utf-8 -*-
from flask import Blueprint


info = Blueprint('info', __name__,
                 template_folder='templates',
                 url_prefix='/info')


from views import *

info/views.py
# -*- coding: utf-8 -*-

"""
    info.views
    ~~~~~~~~~~

    Example additional blueprint.

    :copyright: (c) 2012 by Roman Semirook.
    :license: BSD, see LICENSE for more details.
"""

from flask.templating import render_template
from flask.views import MethodView
from info import info


class HelpPageView(MethodView):

    def get(self):
        return render_template('info/info_page.html')

info.add_url_rule('', view_func=HelpPageView.as_view('help'))

base/templates/base/main.html
{% extends 'layout.html' %}


{% block content %}
    <article class="page l-75-c">
        <header class="page__header">
            <h1 class="page__title">What the hell is it?</h1>
        </header>
        <div class="page__content">
            <p>
                Flask Kit is about Flask project organization.
                It's not yet another Python web-framework, it's not some kind of battery and it's not a layer
                on the top of original Flask.
            </p>
            <blockquote>
                Flask Kit is extendable backbone for your new Flask projects and the set of useful helpers
                to avoid some routine. That's it.
            </blockquote>
            <h2>The main idea of Flask Kit</h2>
            <p>
                Flask is not MVC framework but it's possible to bring some MVC experience with minimum set of
                background magic, with nice and neat project structure and without circular import problems.
            </p>
        </div>
    </article>

    <hr class="l-75-c">

    <article class="page l-75-c">
        <header class="page__header">
            <h1 class="page__title">I don't know what you are talking about!</h1>
        </header>
        <div class="page__content">
            <p>
                Know nothing about Flask? Or, maybe, you need some information to get start? Ok, first of all
                visit <a href="https://github.com/semirook/flask-kit">Flask&nbsp;Kit GitHub page</a>.
                Sure, you have to know Flask itself to write you wonderful web apps. Also, visit
                <a href="http://flask.pocoo.org/extensions/">Flask&nbsp;extensions</a> page, don't write everything
                by yourself.
            </p>
            <aside class="page__errata">
                <ul class="page__errata-list">
                    <li class="page__errata-item"><sup>1)</sup><a href="http://flask.pocoo.org/">Flask main page</a></li>
                    <li class="page__errata-item"><sup>2)</sup><a href="http://flask.pocoo.org/docs/">Flask docs</a></li>
                    <li class="page__errata-item"><sup>3)</sup><a href="http://flask.pocoo.org/extensions/">Flask extensions</a></li>
                </ul>
            </aside>
        </div>
    </article>
{% endblock %}

base/templates/blocks/auth_header.html
{% from "macros/form_helpers.html" import common_form_field, login_form_field %}


{% if current_user.is_anonymous() %}
    <section class="login-header">
        <form action="{{ url_for('base.login') }}" method="POST" class="login-form">
            {{ login_form.hidden_tag() }}
            {{ login_form_field(login_form.email, class_='input login-form__input') }}
            {{ login_form_field(login_form.password, class_='input login-form__input') }}
            <input type="submit" class="button login-form__submit" value="Log in">
        </form>
    </section>
{% else %}
    <section class="login-header login-header_logout">
        <form action="{{ url_for('base.logout') }}" method="POST" class="login-form">
            {{ login_form.hidden_tag() }}
            <input type="submit" class="button login-form__submit" value="Logout">
        </form>
    </section>
{% endif %}

base/templates/blocks/footer.html
<footer class="footer">
    <aside class="footer__author-info l-75-c">
        <img src="{{ my_email|gravatar }}" class="footer__author-avatar">
        <h3 class="footer__author-name">Roman Semirook</h3>
        <p class="footer__author-description">Passionate Python-developer from Kyiv, Ukraine.<br>
            By now I do work in <a href="http://futurecolors.ru">Future Colors</a> company (Moscow, Russia).</p>
    </aside>
</footer>

base/templates/blocks/login_form.html
{% from "macros/form_helpers.html" import common_form_field %}


{% if current_user.is_anonymous() %}
    <form action="{{ url_for('base.login') }}" method="POST" class="common-form">
        {{ form.hidden_tag() }}
        {{ common_form_field(form.email, class_='input common-form__input') }}
        {{ common_form_field(form.password, class_='input common-form__input') }}
        <div class="common-form__field-wrapper">
            <label class="common-form__label">&nbsp;</label>
            <input type="submit" class="button common-form__submit" value="Log in">
        </div>
    </form>
{% else %}
    <div class="page__content">
        <p>You the Boss!</p>
    </div>
{% endif %}

base/templates/blocks/messages.html
{% with messages = get_flashed_messages() %}
    {% if messages %}
        <div class="l-75-c flash-messages">
            <ul class="flash-messages__list">
                {% for message in messages %}
                    <li class="flash-messages__item">{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
{% endwith %}

base/templates/blocks/navigation.html
{% from "macros/form_helpers.html" import render_field %}


<nav class="top-navigation l-75-c">
    <ul class="top-navigation__list">
        {% for nav_item in navigation %}
            <li class="top-navigation__item{% if nav_item.url in request.path  %} top-navigation__item_active{% endif %}">
                {% if request.path != nav_item.url %}
                    <a href="{{ nav_item.url }}" class="top-navigation__item-link">
                {% endif %}
                <span class="top-navigation__item-link-text">{{ nav_item.name }}</span>
                {% if nav_item.counter %}
                    <sup class="top-navigation__item-counter">{{ nav_item.counter }}</sup>
                {% endif %}
                {% if request.path != nav_item.url %}
                    </a>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
</nav>

base/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>{% block page_title %}Flask Kit{% endblock %}</title>
    {% block css %}
        {% assets "css_base" %}
            <link rel="stylesheet" href="{{ ASSET_URL }}">
        {% endassets %}
    {% endblock %}

    {% block js %}
        {% assets "js_base" %}
            <script src="{{ ASSET_URL }}" type="text/javascript"></script>
        {% endassets %}
    {% endblock %}
</head>

<body>
<div class="l-wrapper">
    {% block login_header %}
        {% include 'blocks/auth_header.html' %}
    {% endblock %}
    {% block messages %}
        {% include 'blocks/messages.html' %}
    {% endblock %}
    <header class="header">
        <hgroup class="header__logo-group">
            <h1 class="header__logo"><a href="{{ url_for('base.front_page') }}">Flask Kit</a></h1>
            <h2 class="header__site-remark">for great good</h2>
        </hgroup>
        {% block navigation %}
            {% include 'blocks/navigation.html' %}
        {% endblock %}
    </header>

    {% block content %}{% endblock %}
    {% block paginator %}{% endblock %}

    <div class="l-footer-crosspiece"></div>
</div>

{% block footer %}
    {% include 'blocks/footer.html' %}
{% endblock %}
</body>
</html>

base/templates/login.html
{% extends "layout.html" %}


{% block login_header %}{% endblock %}


{% block content %}
    <article class="page l-75-c">
        <header class="page__header">
            <h1 class="page__title">Example Auth</h1>
        </header>
        {% include 'blocks/login_form.html' %}
    </article>
{% endblock %}

base/templates/macros/form_helpers.html
{% macro common_form_field(field) %}
    <div class="common-form__field-wrapper">
        {% if field.label.text %}
            <label class="common-form__label" for="{{ field.id }}">
                {{ field.label.text }}: {% if field.flags.required %} *{% endif %}
            </label>
        {% endif %}
        {{ field(**kwargs) }}
        {% if field.errors %}
            <div class="form-errors">
                <ul>
                    {% for error in field.errors %}<li>{{ error }}</li>{% endfor %}
                </ul>
            </div>
        {% endif %}
    </div>
{% endmacro %}


{% macro login_form_field(field) %}
    <div class="login-form__field-wrapper">
        {% if field.label.text %}
            <label for="{{ field.id }}">{{ field.label.text }}:&nbsp;</label>
        {% endif %}
        {{ field(**kwargs) }}
    </div>
{% endmacro %}

info/templates/info/info_page.html
{% extends 'layout.html' %}


{% block content %}
    <article class="page l-75-c">
        <header class="page__header">
            <h1 class="page__title">I need more info!</h1>
        </header>
        <div class="page__content">
            <p>
                As I've already said, you can find more info about Flask Kit on
                <a href="https://github.com/semirook/flask-kit">GitHub</a>.
                There is nothing to learn, just follow the proposed project structure.
            </p>
            <p>
                This Kit uses some popular extensions, like 
                <a href="http://packages.python.org/Flask-SQLAlchemy/">Flask-DebugToolbar</a> and
                <a href="http://flask-debugtoolbar.readthedocs.org/en/latest/">Flask-SQLAlchemy</a>.
                Feel free to install more, but don't forget to define them in <code>ext.py</code> and to register them
                in <code>settings.py</code>. You can find examples in the code.
            </p>
        </div>
    </article>
{% endblock %}